### ISSUE TITLE
Berserker enchant for (arms)warrior showing as non-optimal (yellow colored)

### ISSUE THREAD

**Issue by Llamara** [Arbixal/wow-classic-heal-analyser#30]
https://log-summary.bixnpieces.com/#/qD7CHgLjwvPcKm4d

Foully, arms warrior has Berserker enchant on his weapon, but it's showing a yellow coding.

**Comment by Arbixal** [comment]
Yes. The enchants have not been adequately updated for Wrath. I'll do this hopefully soon.

**Comment by Arbixal** [comment]
This particular enchant issue has been resolved. If there are more in the future, feel free to raise a separate issue.

**Comment by Llamara** [comment]
Hi mate, thanks for all your work and the feedback.

Op ma 21 nov. 2022 om 11:45 schreef Caleb ***@***.***>:
