### ISSUE TITLE
Enchant Boots - Vitality not showing as BiS for Arcane Mages

### ISSUE THREAD

**Issue by jadedspirit** [Arbixal/wow-classic-heal-analyser#7]
Hi Guys, 
Not sure if this is working as intended or not but Enchant Boots - Vitality not showing as a BiS option for Arcane Mages (cause we all know how thirsty they are).

**Comment by Arbixal** [comment]
To be honest most of my info comes from Wowhead or icyveins (having not played all specs).

I'm happy to adjust accordingly.
