### ISSUE TITLE
Do you accept PRs?

### ISSUE THREAD

**Issue by theochemtheo** [Arbixal/wow-classic-heal-analyser#8]
Hi there,

I've been using your analyser for the past week and have really liked it. I've found the timeline at the top to be particularly useful. 

Something that I thought could improve it a little bit was adding the timestamp to the tooltip - it helps for planning things like cooldown usage, heroism etc. I took the liberty of trying to add this myself (screenshot below) to a local branch.

![image](https://user-images.githubusercontent.com/20931519/163727479-adc8dc48-8262-49b4-9a55-2685994ada5a.png)

Are you open to pull requests?

Thanks!

**Comment by Arbixal** [comment]
Oof ... I should check this more regularly. Yes, I am open to PRs.

**Comment by Arbixal** [comment]
Looks like a really good change. Thanks for your help.
